# Sendspin E-Ink Display - Hardware Configuration
# ESP32-S3 with 5.65" 7-color ACeP e-ink display
# Roles: metadata + artwork (display-only, no audio)

substitutions:
  # Sendspin role settings
  cover_art_size: "600x600"
  debounce_delay: "5s"
  display_id: eink_display
  # Font sizes for e-ink (smaller than LCD)
  font_title_size: "22"
  font_artist_size: "16"
  font_subtitle_size: "24"
  font_time_size: "96"
  font_date_size: "28"

# Board configuration - ESP32-S3 with PSRAM
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"

esphome:
  platformio_options:
    board_build.flash_mode: dio
    board_build.arduino.memory_type: qio_opi

psram:
  mode: quad
  speed: 80MHz

improv_serial:

# Override base.yaml API timeout for e-ink (refresh blocks 30+ seconds)
api:
  reboot_timeout: 0s

# E-ink specific: boot initialization delay
globals:
  - id: boot_complete
    type: bool
    restore_value: no
    initial_value: "false"

script:
  - id: delayed_boot_init
    then:
      - delay: 10s
      - globals.set:
          id: boot_complete
          value: "true"
      - logger.log: "Boot complete, enabling display updates"
      - component.update: eink_display

wifi:
  on_connect:
    - logger.log: "WiFi connected, starting delayed boot init"
    - script.execute: delayed_boot_init

# E-ink specific: slower clock refresh (15 min vs 1 min for LCD)
interval:
  - interval: 15min
    then:
      - if:
          condition:
            lambda: "return id(boot_complete) && !id(is_playing);"
          then:
            - component.update: eink_display
            - logger.log: "Clock updated (15min interval)"

# Media player state callbacks (display-only device still needs these)
media_player:
  - id: !extend sendspin_media_player
    on_play:
      - globals.set:
          id: is_playing
          value: "true"
    on_pause:
      - globals.set:
          id: is_playing
          value: "false"
      - script.execute: debounced_refresh
    on_idle:
      - globals.set:
          id: is_playing
          value: "false"
      - script.execute: debounced_refresh

# Trigger refresh on track change
text_sensor:
  - id: !extend track_title
    on_value:
      - script.execute: debounced_refresh

# SPI bus for e-ink display
spi:
  clk_pin: GPIO12
  mosi_pin: GPIO11

# E-ink display - 5.65" 7-color ACeP
display:
  - platform: waveshare_epaper
    id: eink_display
    model: 5.65in-f
    cs_pin: GPIO10
    dc_pin: GPIO9
    reset_pin: GPIO8
    busy_pin:
      number: GPIO7
      inverted: true
    rotation: 0
    update_interval: never
    lambda: |-
      // Display: 600 wide x 448 tall

      if (!id(is_playing)) {
        // ============ IDLE SCREEN ============
        it.filled_rectangle(0, 0, 600, 448, id(my_white));
        it.rectangle(20, 20, 560, 408, id(my_black));
        it.strftime(300, 160, id(font_time), id(my_black), TextAlign::CENTER, "%H:%M", id(homeassistant_time).now());
        it.strftime(300, 260, id(font_date), id(my_black), TextAlign::CENTER, "%A, %B %d", id(homeassistant_time).now());
        it.print(300, 380, id(font_idle_subtitle), id(my_black), TextAlign::CENTER, "Sendspin");
      } else {
        // ============ NOW PLAYING SCREEN ============
        it.filled_rectangle(0, 0, 600, 448, id(my_black));
        it.image(0, 0, id(sendspin_cover_art));
        it.filled_rectangle(0, 392, 600, 56, id(my_black));

        std::string title = id(track_title).state;
        std::string artist = id(track_artist).state;
        std::string album = id(album_name).state;

        if (title.empty()) title = "Unknown Track";
        if (title.length() > 45) title = title.substr(0, 42) + "...";

        std::string subtitle;
        if (!artist.empty() && !album.empty()) {
          subtitle = artist + " - " + album;
        } else if (!artist.empty()) {
          subtitle = artist;
        } else if (!album.empty()) {
          subtitle = album;
        }
        if (subtitle.length() > 60) subtitle = subtitle.substr(0, 57) + "...";

        it.print(12, 400, id(font_title), id(my_white), TextAlign::TOP_LEFT, title.c_str());
        if (!subtitle.empty()) {
          it.print(12, 424, id(font_artist), id(my_white), TextAlign::TOP_LEFT, subtitle.c_str());
        }
      }
