# M5Stack Tab5 with Sendspin - Firmware Build Configuration
# Original config by @balloob (Paulus Schoutsen)
# Roles: base + metadata + artwork + player + controller (full featured)

substitutions:
  device_name: sendspin-tab5
  friendly_name: "Sendspin Tab5"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  min_version: 2025.5.0
  project:
    name: "diy-esphome.sendspin-tab5"
    version: !env_var FIRMWARE_VERSION dev

dashboard_import:
  package_import_url: github://heytcass/diy-esphome-devices/firmware/sendspin-tab5.yaml@main
  import_full_config: false

packages:
  # Core infrastructure
  base: !include ../common/base.yaml
  diagnostics: !include ../common/diagnostics.yaml
  # Sendspin roles (full featured: all roles)
  sendspin_base: !include ../common/sendspin/base.yaml
  sendspin_metadata: !include ../common/sendspin/metadata.yaml
  sendspin_artwork: !include ../common/sendspin/artwork.yaml
  sendspin_player: !include ../common/sendspin/player.yaml
  sendspin_controller: !include ../common/sendspin/controller.yaml
  # Device hardware
  hardware: !include ../devices/sendspin/tab5.yaml
